nostra/models/__init__.py
__author__ = 'willmcginnis'

nostra/models/post.py
import datetime as dt

from nostra.extensions import db
from nostra.models.relationships import tags_posts
from nostra.database import (
    Column,
    Model,
    SurrogatePK,
)


class Post(SurrogatePK, Model):

    __tablename__ = 'posts'

    title = db.Column(db.Text)
    slug = db.Column(db.Text)
    body = db.Column(db.Text)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)

    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    tags = db.relationship('Tag', secondary=tags_posts, backref=db.backref('posts_br', lazy='dynamic'))

    def __init__(self, title, slug, body, **kwargs):
        db.Model.__init__(self, title=title, slug=slug, body=body, **kwargs)

nostra/forms/__init__.py
__author__ = 'willmcginnis'

nostra/forms/public.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired

from nostra.models.user import User


class LoginForm(Form):
    username = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Unknown username')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.active:
            self.username.errors.append('User not activated')
            return False
        return True

nostra/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template
import os

from nostra.settings import ProdConfig
from nostra.assets import assets
from nostra.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    mail,
    migrate,
    debug_toolbar,
)
from nostra.views import public, user, blog


def create_app(config_object=ProdConfig):
    """An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)

    if config_object == ProdConfig:
        app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URL']

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app

def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    return None


def register_blueprints(app):
    app.register_blueprint(public.blueprint)
    app.register_blueprint(user.blueprint)
    app.register_blueprint(blog.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

nostra/services/__init__.py
__author__ = 'willmcginnis'

nostra/views/__init__.py
__author__ = 'willmcginnis'

nostra/views/admin.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import Blueprint, request

from flask_login import login_required, current_user
from nostra.utils import flash_errors, render_extensions
from nostra.models.post import Post

blueprint = Blueprint('admin', __name__, static_folder="../static")


@blueprint.route("/new_blog", methods=["GET", "POST"])
@login_required
def new_blog():
    if not current_user.is_admin:
        return render_extensions('401.html')

    if request.method == 'POST':
        try:
            content = str(request.form['content'])
        except Exception:
            content = ''

        try:
            slug = str(request.form['slug'])
        except Exception:
            slug = ''

        try:
            title = str(request.form['title'])
        except Exception:
            title = ''

        post = Post(title=title, body=content, slug=slug)
        post.save()

        current_user.posts.append(post)
        current_user.save()

    return render_extensions('admin/new_blog.html')

@blueprint.route("/edit_blog/<blog_id>/", methods=["GET", "POST"])
@login_required
def edit_blog(blog_id):
    if not current_user.is_admin:
        return render_extensions('401.html')

    if request.method == 'POST':
        try:
            content = str(request.form['content'])
        except Exception:
            content = ''

        try:
            slug = str(request.form['slug'])
        except Exception:
            slug = ''

        try:
            title = str(request.form['title'])
        except Exception:
            title = ''

        post = Post(title=title, body=content, slug=slug)
        post.save()

        current_user.posts.append(post)
        current_user.save()

    post_obj = Post.query.filter_by(id=int(blog_id)).first()
    post_content = {
        'title': str(post_obj.title),
        'slug': str(post_obj.slug),
        'body': str(post_obj.body),
    }

    return render_extensions('admin/edit_blog.html', post=post_content)

nostra/views/blog.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import Blueprint

from nostra.services.blog import get_page, get_post_detail
from nostra.utils import flash_errors, render_extensions

blueprint = Blueprint('blog', __name__, static_folder="../static")


@blueprint.route("/blog/<page>/", methods=["GET"])
def blog_page(page=None):
    """

    :param page:
    :return:
    """

    page = int(page)
    _page_size = 3  # TODO: move into settings

    if page is None or page <= 0:
        next_page = 0
        prev_page = 1
        current = True
    else:
        next_page = page - 1
        prev_page = page + 1
        current = False

    posts = get_page(_page_size, page)

    return render_extensions("blog/blog_page.html", posts=posts, next_page=next_page, prev_page=prev_page, current=current)


@blueprint.route("/post_detail/<pk>/", methods=["GET"])
def blog_detail(pk):
    """

    :param pk:
    :return:
    """

    post = get_post_detail(int(pk))
    return render_extensions("blog/blog_detail.html", post=post)

nostra/views/public.py
# -*- coding: utf-8 -*-
"""Public section, including homepage and signup."""
from flask import (Blueprint, request, render_template, flash, url_for, send_from_directory, make_response,
                   redirect, current_app)
import datetime

from flask_login import login_user, login_required, logout_user

from nostra.extensions import login_manager
from nostra.models.user import User
from nostra.forms.public import LoginForm
from nostra.forms.user import RegisterForm
from nostra.utils import flash_errors, render_extensions
from nostra.database import db


blueprint = Blueprint('public', __name__, static_folder="../static")


@login_manager.user_loader
def load_user(id):
    return User.get_by_id(int(id))


@blueprint.route("/", methods=["GET", "POST"])
def home():
    form = LoginForm(request.form)
    # Handle logging in
    if request.method == 'POST':
        if form.validate_on_submit():
            login_user(form.user)
            flash("You are logged in.", 'success')
            redirect_url = request.args.get("next") or url_for("user.profile")
            return redirect(redirect_url)
        else:
            flash_errors(form)
    return render_extensions("public/home.html", form=form)


@blueprint.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('You are logged out.', 'info')
    return redirect(url_for('public.home'))


@blueprint.route("/register/", methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        new_user = User.create(username=form.username.data,
                               first_name=form.first_name.data,
                               last_name=form.last_name.data,
                               email=form.email.data,
                               password=form.password.data,
                               active=True)
        flash("Thank you for registering. You can now log in.", 'success')
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)
    return render_extensions('public/register.html', form=form)


@blueprint.route("/about/")
def about():
    form = LoginForm(request.form)
    return render_extensions("public/about.html", form=form)

@blueprint.route('/robots.txt')
@blueprint.route('/favicon.ico')
def static_from_root():
    return send_from_directory(current_app.static_folder, request.path[1:])

@blueprint.route('/sitemap.xml', methods=['GET'])
def sitemap():
    """
    Generate sitemap.xml. Makes a list of urls and date modified.
    """
    pages = []
    ten_days_ago = datetime.datetime.now() - datetime.timedelta(days=10)
    ten_days_ago = ten_days_ago.date().isoformat()
    # static pages
    for rule in current_app.url_map.iter_rules():
        if "GET" in rule.methods and len(rule.arguments) == 0:
            pages.append([rule.rule, ten_days_ago])

    sitemap_xml = render_template('public/sitemap_template.xml', pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"

    return response

nostra/views/user.py
# -*- coding: utf-8 -*-
from flask import (Blueprint, request, render_template, flash, send_file, url_for, send_from_directory, make_response,
                   redirect, current_app)

from flask_login import login_required, logout_user, current_user
from nostra.utils import flash_errors, render_extensions
from nostra.forms.user import PasswordForm, EmailForm, UsernameForm, CompanyForm
from nostra.extensions import mail
from nostra.models.user import User
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
import urllib, json
from openpyxl import Workbook, load_workbook


blueprint = Blueprint("user", __name__, url_prefix='/users',
                      static_folder="../static")


@blueprint.route("/", methods=["GET", "POST"])
@login_required
def profile():
    form = CompanyForm()
    if form.validate_on_submit():

        urlIS = 'http://edgaronline.api.mashery.com/v1/corefinancials?primarysymbols='+str(form.ticker.data)+'&conceptgroups=IncomeStatementConsolidated&appkey=anapqb65c25p9pr9twjapaj3'
        urlBS = 'http://edgaronline.api.mashery.com/v1/corefinancials?primarysymbols='+str(form.ticker.data)+'&conceptgroups=BalanceSheetConsolidated&appkey=anapqb65c25p9pr9twjapaj3'
        urlCFS = 'http://edgaronline.api.mashery.com/v1/corefinancials?primarysymbols='+str(form.ticker.data)+'&conceptgroups=CashFlowStatementConsolidated&appkey=anapqb65c25p9pr9twjapaj3'

        #testurl = urlIS = 'http://edgaronline.api.mashery.com/v1/corefinancials?primarysymbols=MSFT&conceptgroups=BalanceSheetConsolidated&appkey=anapqb65c25p9pr9twjapaj3'
        response = urllib.urlopen(urlIS)
        dataIS = json.loads(response.read())
        response = urllib.urlopen(urlBS)
        dataBS = json.loads(response.read())
        response = urllib.urlopen(urlCFS)
        dataCFS = json.loads(response.read())

        #import Workbook
        wb2 = load_workbook('nostra/OperatingModelTemplate.xlsx')
        wb1=wb2
        ws1=wb1.active

        print "DATA FOR INCOME STATEMENT"
        for x in range(0, 4):
            for y in range(0, 25):
                for cell in ws1['B']:
                    if str(cell.value) == 'I'+str(y):
                        if x == 0:
                            ws1['C' + str(cell.row)].value = dataIS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 1:
                            ws1['D' + str(cell.row)].value = dataIS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 2:
                            ws1['E' + str(cell.row)].value = dataIS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 3:
                            ws1['F' + str(cell.row)].value = dataIS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']

        print "DATA FOR BALANCE SHEET"
        for x in range(0, 4):
            for y in range(0, 42):

                for cell in ws1['B']:
                    if str(cell.value) == 'B'+str(y):
                        if x == 0:
                            ws1['C' + str(cell.row)].value = dataBS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x ==1:
                            ws1['D' + str(cell.row)].value = dataBS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 2:
                            ws1['E' + str(cell.row)].value = dataBS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 3:
                            ws1['F' + str(cell.row)].value = dataBS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']


        print "DATA FOR CASH FLOW STATEMENT"
        for x in range(0, 4):
            for y in range(0, 39):
                for cell in ws1['B']:
                    if str(cell.value) == 'C'+str(y):
                        if x == 0:
                            ws1['C' + str(cell.row)].value = dataCFS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 1:
                            ws1['D' + str(cell.row)].value = dataCFS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 2:
                            ws1['E' + str(cell.row)].value = dataCFS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']
                        elif x == 3:
                            ws1['F' + str(cell.row)].value = dataCFS['result']['rowset'][x]['groups'][0]['rowset'][y]['value']

        wb1.save('nostra/OperationalModelComplete.xlsx')
        return redirect(url_for('user.download'))
    else:
        flash_errors(form)
    print "is this happening"
    return render_extensions("users/profile.html", companyform=form)

@blueprint.route('/download', methods=["GET"])
@login_required
def download():
    return send_file('OperationalModelComplete.xlsx', as_attachment=True)

@blueprint.route('/reset', methods=["GET", "POST"])
def reset():
    form = EmailForm()
    if form.validate_on_submit():
        emailuser = User.query.filter_by(email=form.email.data).first_or_404()

        subject = "Password reset requested"
        from nostra.settings import Config

        ts = URLSafeTimedSerializer(Config.SECRET_KEY)
        token = ts.dumps(emailuser.email, salt='recover-key')

        recover_url = url_for('user.reset_with_token', token=token, _external=True)
        html = render_template('email/recover.html', recover_url=recover_url)

        msg = Message(html=html, recipients=[emailuser.email], subject=subject)
        mail.send(msg)

        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_extensions('users/reset.html', resetform=form)

@blueprint.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        from nostra.settings import Config

        ts = URLSafeTimedSerializer(Config.SECRET_KEY)
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        return render_template("404.html")

    form = PasswordForm()

    if form.validate_on_submit():
        emailuser = User.query.filter_by(email=email).first_or_404()
        emailuser.set_password(form.password.data)
        emailuser.save()
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_extensions('users/reset_with_token.html', resetform=form, token=token)


@blueprint.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        current_user.save()
        return redirect(url_for('user.profile'))
    else:
        flash_errors(form)

    return render_extensions('users/change_password.html', resetform=form)


@blueprint.route('/change_username', methods=['GET', 'POST'])
@login_required
def change_username():
    form = UsernameForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.save()
        return redirect(url_for('user.profile'))
    else:
        flash_errors(form)

    return render_extensions('users/change_username.html', resetform=form)

@blueprint.route('/unsubscribe')
@login_required
def unsubscribe():
    return render_extensions('users/unsubscribe.html')


@blueprint.route('/unsubscribe_confirm')
@login_required
def unsubscribe_confirm():
    user = current_user
    user.username = '%s (Unsubscribed)' % (user.username,)
    user.email = '%s (Unsubscribed)' % (user.email,)
    user.is_admin = False
    user.active = False
    user.save()
    logout_user()
    return redirect(url_for('public.home'))

nostra/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

nostra/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© James Baker</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:james.baker@yale.edu">Contact</a></li>
    </ul>
  </small>
</footer>

nostra/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}

    Finostra

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  <script>{{ _GOOGLE_ANALYTICS }}</script>

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}
<script type="text/javascript" src="{{ url_for('static', filename='libs/jQuery/dist/jquery.js')}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='libs/bootstrap/dist/js/bootstrap.js')}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/plugins.js')}}"></script>
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

nostra/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      Finostra

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
        <li><a href="{{ url_for('blog.blog_page', page=0) }}">Blog</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated() %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.profile') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Account <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('user.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('user.change_username') }}">Change Username</a></li>
                        <li><a href="{{ url_for('user.unsubscribe') }}">Unsubscribe</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('public.logout') }}">Logout</a></li>
                    </ul>
                </li>
    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
      <li><a href="{{ url_for('user.reset') }}">Forgot password</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>